apiVersion: v1
kind: Service
metadata:
  labels:
    app: edc-consumer
    app.kubernetes.io/instance: edc-consumer
  name: edc-consumer
  namespace: product-material-pass
spec:
  ports:
    - name: http
      port: 9191
      protocol: TCP
      targetPort: http
    - name: http-ids
      port: 9292
      protocol: TCP
      targetPort: http-ids
    - name: http-data
      port: 9192
      protocol: TCP
      targetPort: http-data
  selector:
    app: edc-consumer
  type: ClusterIP