apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: edc-provider
    app.kubernetes.io/instance: edc-provider
  name: edc-provider
  namespace: product-material-pass
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: edc-provider
  template:
    metadata:
      labels:
        app: edc-provider
    spec:
      containers:
        - image: muhammadsaudkhan/edc-provider
          volumeMounts:
            - name: data
              mountPath: /app/samples/04.0-file-transfer/data/
          imagePullPolicy: Always
          name: edc-provider
          ports:
            - containerPort: 8181
              name: http
              protocol: TCP
            - containerPort: 8282
              name: http-ids
              protocol: TCP
            - containerPort: 8182
              name: http-data
              protocol: TCP
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: edc-pvc