apiVersion: v1
kind: Service
metadata:
  labels:
    app: edc-provider
    app.kubernetes.io/instance: edc-provider
  name: edc-provider
  namespace: product-material-pass
spec:
  ports:
    - name: http
      port: 8181
      protocol: TCP
      targetPort: 8181
    - name: http-ids
      port: 8282
      protocol: TCP
      targetPort: 8282
    - name: http-data
      port: 8182
      protocol: TCP
      targetPort: 8182
  selector:
    app: edc-provider
  type: ClusterIP