apiVersion: v1
kind: Service
metadata:
  labels:
    app: edc-provider
    app.kubernetes.io/instance: edc-provider
  name: edc-provider
  #namespace: product-material-pass
  namespace: default
spec:
  ports:
    - name: http
      port: 8181
      protocol: TCP
      targetPort: http
    - name: http-ids
      port: 8282
      protocol: TCP
      targetPort: http-ids
    - name: http-data
      port: 8182
      protocol: TCP
      targetPort: http-data
  selector:
    app: edc-provider
  type: ClusterIP