apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edc-pvc
  namespace: product-material-pass
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi