apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld
    app.kubernetes.io/instance: helloworld
  name: helloworld
  namespace: product-material-pass
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: helloworld