apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-ui
    app.kubernetes.io/instance: nginx-ui
  name: nginx-ui
  namespace: product-material-pass
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: nginx-ui