apiVersion: v1
kind: Service
metadata:
  name: {{ include "edc-provider.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "edc-provider.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    # - port: {{ .Values.service.port }}
    #   targetPort: http
    #   protocol: TCP
    #   name: http
    - port: 8181
      targetPort: http
      protocol: TCP
      name: http
    - port: 8282
      targetPort: http-ids
      protocol: TCP
      name: http-ids
    - port: 8182
      targetPort: http-data
      protocol: TCP
      name: http-data
  selector:
    {{- include "edc-provider.selectorLabels" . | nindent 4 }}
