'
'  Copyright (c) 2022 Microsoft Corporation
'
'  This program and the accompanying materials are made available under the
'  terms of the Apache License, Version 2.0 which is available at
'  https://www.apache.org/licenses/LICENSE-2.0
'
'  SPDX-License-Identifier: Apache-2.0
'
'  Contributors:
'       Microsoft - Initial Draft
'
'

@startuml

!pragma layout smetana

skinParam NoteBackgroundColor WhiteSmoke
skinParam NoteFontColor Black
skinParam ParticipantBackgroundColor WhiteSmoke
skinParam ActorBackgroundColor WhiteSmoke
skinParam AgentBackgroundColor White
skinParam AgentBorderColor SkyBlue
skinparam shadowing false

!define ConsumerColor f8f2ff
!define ProviderColor d9edff
!define WarningColor Business
!define LeadColor Technology

agent PA as "Participant\nAgent"
agent Connector as "Connector"
agent FCC as "Federated\nCatalog Crawler"
agent FCN as "Federated\nCatalog Node"
agent Application

PA <|-- Connector
PA <|-- FCC
PA <|-- FCN
PA <|-- Application
Connector --> Connector : Interacts with
FCC -right-> FCN : Crawls

@enduml
