'
'  Copyright (c) 2022 Microsoft Corporation
'
'  This program and the accompanying materials are made available under the
'  terms of the Apache License, Version 2.0 which is available at
'  https://www.apache.org/licenses/LICENSE-2.0
'
'  SPDX-License-Identifier: Apache-2.0
'
'  Contributors:
'       Microsoft - Initial Draft
'
'

@startuml

!pragma layout smetana

skinParam NoteBackgroundColor WhiteSmoke
skinParam NoteFontColor Black
skinParam ParticipantBackgroundColor WhiteSmoke
skinParam ActorBackgroundColor WhiteSmoke
skinParam AgentBackgroundColor White
skinParam AgentBorderColor SkyBlue
skinparam shadowing false

!define ConsumerColor f8f2ff
!define ProviderColor d9edff
!define WarningColor Business
!define LeadColor Technology

agent Participant
agent PA as "Participant\nAgent"
agent IDP as "Identity\nProvider"
agent Dataspace
agent DataspaceAuthority as "Dataspace\nAuthority"
agent Registry as "Dataspace \nRegistry"

Participant -down-> PA : runs\n1..n
Participant --> Participant : establishes relationships with
PA --> PA: Interacts with
PA -left-> IDP : trusts\n1..n
PA --> Dataspace : participates in\n1..n
PA --> Registry : looks up\n0..n
Dataspace --> DataspaceAuthority : managed by\n0..n
DataspaceAuthority -right-> Registry : approves
DataspaceAuthority -up-> IDP: approves\n0..n

@enduml
