apiVersion: v1
kind: PersistentVolume
metadata:
  name: edc-pv
  labels:
    type: local
  namespace: product-material-pass
spec:
  storageClassName: default
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"