apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: nginx
    command: ["/bin/sh", "-c"]
    args: 
    - curl "http://edc-provider:8182/data/assets";
    - echo starting;
    - ls -l;
    - echo done;
  restartPolicy: OnFailure