apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: edc-consumer
    app.kubernetes.io/instance: edc-consumer
  name: edc-consumer
  namespace: product-material-pass
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: edc-consumer
  template:
    metadata:
      labels:
        app: edc-consumer
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
          imagePullPolicy: IfNotPresent
          name: edc-consumer
          ports:
            - containerPort: 9191
              name: http
              protocol: TCP
            - containerPort: 9292
              name: http-ids
              protocol: TCP
            - containerPort: 9192
              name: http-data
              protocol: TCP