apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dataspace-connector.fullname" . }}-envvars
  labels:
    {{- include "dataspace-connector.labels" . | nindent 4 }}
data:
  {{- range $envName, $value := .Values.edc.env }}
  {{ $envName | quote }}: {{ $value | quote }}
  {{- end }}
  WEB_HTTP_PORT: {{ .Values.edc.port | quote }}
  WEB_HTTP_PATH: {{ .Values.edc.path | quote }}
  WEB_HTTP_IDS_PORT: {{ .Values.edc.idsApi.port | quote }}
  WEB_HTTP_IDS_PATH: {{ .Values.edc.idsApi.path | quote }}
  {{ if eq .Values.edc.managementApi.enabled true }}
  WEB_HTTP_DATA_PORT: {{ .Values.edc.managementApi.port | quote }}
  WEB_HTTP_DATA_PATH: {{ .Values.edc.managementApi.path | quote }}
  {{ end }}
