apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dataspace-connector.fullname" . }}
  labels:
    {{- include "dataspace-connector.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dataspace-connector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dataspace-connector.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.edc.port }}
              protocol: TCP
            - name: http-ids
              containerPort: {{ .Values.edc.idsApi.port }}
              protocol: TCP
            {{ if .Values.edc.managementApi.enabled }}
            - name: http-mgmt
              containerPort: {{ .Values.edc.managementApi.port }}
              protocol: TCP
            {{ end }}
          envFrom:
            - configMapRef:
                name: {{ include "dataspace-connector.fullname" . }}-envvars
            - secretRef:
                name: {{ include "dataspace-connector.fullname" . }}-envvars
          livenessProbe:
            httpGet:
              path: /api/check/liveness
              port: http
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /api/check/readiness
              port: http
            initialDelaySeconds: 10
          startupProbe:
            httpGet:
              path: /api/check/liveness
              port: http
            failureThreshold: 60
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
