openapi: 3.0.1
paths:
  /contractnegotiations/{id}/cancel:
    post:
      tags:
      - Contract Negotiation
      operationId: cancelNegotiation
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /contractnegotiations/{id}/decline:
    post:
      tags:
      - Contract Negotiation
      operationId: declineNegotiation
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /contractnegotiations/{id}/agreement:
    get:
      tags:
      - Contract Negotiation
      operationId: getAgreementForNegotiation
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContractAgreementDto'
  /contractnegotiations/{id}:
    get:
      tags:
      - Contract Negotiation
      operationId: getNegotiation
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContractNegotiationDto'
  /contractnegotiations/{id}/state:
    get:
      tags:
      - Contract Negotiation
      operationId: getNegotiationState
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NegotiationState'
  /contractnegotiations:
    get:
      tags:
      - Contract Negotiation
      operationId: getNegotiations
      parameters:
      - name: offset
        in: query
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        schema:
          type: integer
          format: int32
      - name: filter
        in: query
        schema:
          type: string
      - name: sort
        in: query
        schema:
          type: string
          enum:
          - ASC
          - DESC
      - name: sortField
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ContractNegotiationDto'
    post:
      tags:
      - Contract Negotiation
      operationId: initiateContractNegotiation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NegotiationInitiateRequestDto'
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NegotiationId'
components:
  schemas:
    ContractAgreementDto:
      type: object
      properties:
        id:
          type: string
        providerAgentId:
          type: string
        consumerAgentId:
          type: string
        contractSigningDate:
          type: integer
          format: int64
        contractStartDate:
          type: integer
          format: int64
        contractEndDate:
          type: integer
          format: int64
        assetId:
          type: string
        policyId:
          type: string
    ContractNegotiationDto:
      type: object
      properties:
        contractAgreementId:
          type: string
        counterPartyAddress:
          type: string
        errorDetail:
          type: string
        id:
          type: string
        protocol:
          type: string
        state:
          type: string
        type:
          type: string
          enum:
          - CONSUMER
          - PROVIDER
    NegotiationState:
      type: object
      properties:
        state:
          type: string
    NegotiationId:
      type: object
      properties:
        id:
          type: string
    Action:
      type: object
      properties:
        type:
          type: string
        includedIn:
          type: string
        constraint:
          $ref: '#/components/schemas/Constraint'
    Constraint:
      required:
      - edctype
      type: object
      properties:
        edctype:
          type: string
      discriminator:
        propertyName: edctype
    ContractOfferDescription:
      required:
      - assetId
      - offerId
      type: object
      properties:
        offerId:
          type: string
        assetId:
          type: string
        policyId:
          type: string
        policy:
          $ref: '#/components/schemas/Policy'
    Duty:
      type: object
      properties:
        uid:
          type: string
        target:
          type: string
        action:
          $ref: '#/components/schemas/Action'
        assignee:
          type: string
        assigner:
          type: string
        constraints:
          type: array
          items:
            $ref: '#/components/schemas/Constraint'
        parentPermission:
          $ref: '#/components/schemas/Permission'
        consequence:
          $ref: '#/components/schemas/Duty'
    NegotiationInitiateRequestDto:
      required:
      - connectorAddress
      - connectorId
      - offer
      - protocol
      type: object
      properties:
        connectorAddress:
          type: string
        protocol:
          type: string
        connectorId:
          type: string
        offer:
          $ref: '#/components/schemas/ContractOfferDescription'
    Permission:
      type: object
      properties:
        uid:
          type: string
        target:
          type: string
        action:
          $ref: '#/components/schemas/Action'
        assignee:
          type: string
        assigner:
          type: string
        constraints:
          type: array
          items:
            $ref: '#/components/schemas/Constraint'
        duties:
          type: array
          items:
            $ref: '#/components/schemas/Duty'
    Policy:
      type: object
      properties:
        uid:
          type: string
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/Permission'
        prohibitions:
          type: array
          items:
            $ref: '#/components/schemas/Prohibition'
        obligations:
          type: array
          items:
            $ref: '#/components/schemas/Duty'
        extensibleProperties:
          type: object
          additionalProperties:
            type: object
        inheritsFrom:
          type: string
        assigner:
          type: string
        assignee:
          type: string
        target:
          type: string
        '@type':
          type: string
          enum:
          - SET
          - OFFER
          - CONTRACT
    Prohibition:
      type: object
      properties:
        uid:
          type: string
        target:
          type: string
        action:
          $ref: '#/components/schemas/Action'
        assignee:
          type: string
        assigner:
          type: string
        constraints:
          type: array
          items:
            $ref: '#/components/schemas/Constraint'
