openapi: 3.0.1
paths:
  /callback:
    post:
      operationId: callWebhook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProvisionerWebhookRequest'
      responses:
        default:
          description: default response
          content:
            application/json: {}
components:
  schemas:
    DataAddress:
      type: object
      properties:
        properties:
          type: object
          additionalProperties:
            type: string
    ProvisionerWebhookRequest:
      type: object
      properties:
        transferProcessId:
          type: string
        resourceDefinitionId:
          type: string
        assetId:
          type: string
        resourceName:
          type: string
        contentDataAddress:
          $ref: '#/components/schemas/DataAddress'
        apiToken:
          type: string
        hasToken:
          type: boolean
