openapi: 3.0.1
paths:
  /check/health:
    get:
      tags:
      - Application Observability
      operationId: checkHealth
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /check/liveness:
    get:
      tags:
      - Application Observability
      operationId: getLiveness
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /check/readiness:
    get:
      tags:
      - Application Observability
      operationId: getReadiness
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /check/startup:
    get:
      tags:
      - Application Observability
      operationId: getStartup
      responses:
        default:
          description: default response
          content:
            application/json: {}
