openapi: 3.0.1
paths:
  /transferprocess/{id}/cancel:
    post:
      tags:
      - Transfer Process
      operationId: cancelTransferProcess
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /transferprocess/{id}/deprovision:
    post:
      tags:
      - Transfer Process
      operationId: deprovisionTransferProcess
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /transferprocess:
    get:
      tags:
      - Transfer Process
      operationId: getAllTransferProcesses
      parameters:
      - name: offset
        in: query
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        schema:
          type: integer
          format: int32
      - name: filter
        in: query
        schema:
          type: string
      - name: sort
        in: query
        schema:
          type: string
          enum:
          - ASC
          - DESC
      - name: sortField
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransferProcessDto'
    post:
      tags:
      - Transfer Process
      operationId: initiateTransfer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequestDto'
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: string
  /transferprocess/{id}:
    get:
      tags:
      - Transfer Process
      operationId: getTransferProcess
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferProcessDto'
  /transferprocess/{id}/state:
    get:
      tags:
      - Transfer Process
      operationId: getTransferProcessState
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    DataRequestDto:
      type: object
      properties:
        assetId:
          type: string
        contractId:
          type: string
        connectorId:
          type: string
    TransferProcessDto:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        state:
          type: string
        errorDetail:
          type: string
        dataRequest:
          $ref: '#/components/schemas/DataRequestDto'
    DataAddress:
      type: object
      properties:
        properties:
          type: object
          additionalProperties:
            type: string
    TransferRequestDto:
      type: object
      properties:
        connectorAddress:
          type: string
        contractId:
          type: string
        dataDestination:
          $ref: '#/components/schemas/DataAddress'
        managedResources:
          type: boolean
        properties:
          type: object
          additionalProperties:
            type: string
        transferType:
          $ref: '#/components/schemas/TransferType'
        protocol:
          type: string
        connectorId:
          type: string
        assetId:
          type: string
    TransferType:
      type: object
      properties:
        contentType:
          type: string
        isFinite:
          type: boolean
