name: "Publish docker images"

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    # tags: [ 'v*.*.*' ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  EDC_CONSUMER_IMAGE_NAME: "edc-consumer"
  EDC_PROVIDER_IMAGE_NAME: "edc-provider"
  CONSUMER_UI_IMAGE_NAME: "consumer-ui"
  REPOSITORY_NAME: "muhammadsaudkhan"
  IMAGE_TAG: "v1.PI4.S4"
  #COMMIT_SHA: ${{ github.sha }}
    
jobs:
  build:

    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      #- name: Setup nodejs
      #  uses:  actions/setup-node@v2
      #  with:
      #    - node-version: 16
      #- name: Install packages
      #  run: npm install --legacy-peer-deps
      #- name: Create production distribution
      #  run: npm run build

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      #- name: Extract Docker metadata
      #  id: meta
      #  uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #  with:
      #    images: ${{ env.REPOSITORY_NAME }}/${{ env.CONSUMER_UI_IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image - edc-consumer
        id: build-and-push-consumer
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: docker/edc-consumer
          push: true
          tags: ${{ env.REPOSITORY_NAME }}/${{ env.EDC_CONSUMER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          labels: labels

      - name: Build and push Docker image - edc-provider
        id: build-and-push-provider
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: docker/edc-provider
          push: true
          tags: ${{ env.REPOSITORY_NAME }}/${{ env.EDC_PROVIDER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          labels: labels

      - name: Build and push Docker image - consumer-ui
        id: build-and-push-frontend
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: docker/consumer-ui
          push: true
          tags: ${{ env.REPOSITORY_NAME }}/${{ env.CONSUMER_UI_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          labels: labels
          #tags: ${{ steps.meta.outputs.tags }}
          #labels: ${{ steps.meta.outputs.labels }}